name: pos_desktop
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"
  #flutter: '>=1.5.9-pre.270'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  aiframework: ^1.0.7+39
  draggable_scrollbar: ^0.0.4
  responsive_scaffold: ^1.3.0+2
  intl: any
  scroll_to_index: ^1.0.6
  pattern_formatter: ^0.0.3
  marquee: ^1.3.1
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Rubik-Black.ttf
          weight: 900
        - asset: fonts/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
    - family : SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Thin.ttf
          weight: 100
        - asset: fonts/SFProDisplay-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/SFProDisplay-Ultralight.ttf
          weight: 200
        - asset: fonts/SFProDisplay-UltralightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SFProDisplay-Light.ttf
          weight: 300
        - asset: fonts/SFProDisplay-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: fonts/SFProDisplay-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: fonts/SFProDisplay-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: fonts/SFProDisplay-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: fonts/SFProDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SFProDisplay-Heavy.ttf
          weight: 800
        - asset: fonts/SFProDisplay-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SFProDisplay-Black.ttf
          weight: 900
        - asset: fonts/SFProDisplay-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Tes
      fonts:
        - asset: fonts/HackRegular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
